### PR TITLE
Add instructions to generate a kubeconfig for TLS authentication

### PR DESCRIPTION
**Pull request by samuelvl**
Create additional kubeconfigs to authenticate users using TLS certificates

### CODE REVIEW

**Comment by e-minguez** [comment]
Can you remove the `bash` stuff in the code blocks? The theme renders those blocks differently and some unaligned :(

**Comment by e-minguez** [comment]
I'm assuming this has been tested right? :sweat_smile: If so, LGTM and I will merge it.

**Comment by samuelvl** [comment]
> I'm assuming this has been tested right? sweat_smile If so, LGTM and I will merge it.

It's been tested in my local environment yep

**Comment by e-minguez** [comment]
> > I'm assuming this has been tested right? sweat_smile If so, LGTM and I will merge it.
> 
> It's been tested in my local environment yep

Great. Can you please rebase your commits so I can merge it? Thanks!

**Comment by e-minguez** [comment]
Merged, thanks!

**Pull request merged**
