### PR TITLE
New oc adm release info examples

### PR DESCRIPTION
**Pull request by palonsoro**
New interesting `oc adm release info` examples that provide extra info of each release

### CODE REVIEW

**Comment by e-minguez** [comment]
Thanks for the PR! Could you please take a look at https://openshift.tips/oc/#dump-openshift-release-information ? I guess the tips in your PR are more aligned to that section (?)
Thanks.

**Comment by palonsoro** [comment]
I'll move them there

**Comment by palonsoro** [comment]
Fixed

**Comment by e-minguez** [comment]
Merged, thanks!

**Pull request merged**
